# configs/config.yaml

# Device configuration
device: 'cuda'

# Dataset and DataLoader parameters
data_dir: './data'
img_size: 224
batch_size: 64
num_workers: 0 # increase for faster data loading

# Model parameters
model_name: 'vit_tiny_patch16_224'
num_classes: 10
pretrained: true

# Training parameters
num_epochs: 3
learning_rate: 0.0001
weight_decay: 0.00001
mixed_precision: true

# Output and logging
checkpoint_dir: './checkpoints'